### ISSUE TITLE
Header elements make unexpected behaviors as window dimensions change

### ISSUE THREAD

**Issue by ins4w** [ins4w/cryptopunks-clone#4]
![image](https://user-images.githubusercontent.com/66014666/146572741-36c4812c-cbe2-4cca-9491-b8672e2a20ae.png)

**Comment by HASCA-GH** [comment]
Just working in order to fix the bug

**Comment by HASCA-GH** [comment]
I just made the pull request. 
Check it out, please in the pull request.
If everything is ok, we may close this issue.

**Comment by ins4w** [comment]
Fixed and tested.
